---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authors":
    post:
      summary: Creates an author
      tags:
      - Authors
      parameters: []
      responses:
        '201':
          description: Author created
        '403':
          description: Invalid permission rule
        '500':
          description: Invalid permission rule
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                locale:
                  type: string
                  default: ru || en
              required:
              - name
              - surnameemail
  "/authors/{id}":
    delete:
      summary: Retrieves a author
      tags:
      - Authors
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Author delete
        '404':
          description: Author not found
        '403':
          description: Invalid permission rule
        '500':
          description: Invalid permission rule
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
